#!/usr/bin/env bash

REPO_URL="https://github.com/icpz/debian-bootstrap"
BASEDIR=""

bs_log() {
    echo "$@"
}

check_root() {
    local _uid="$(id -u)"
    if [ "$_uid" -ne 0 ]; then
        bs_log "the script MUST be run as root"
        exit -1
    fi
}

check_cmd() {
    local _cmd="$1"
    if ! command -v "${_cmd}" > /dev/null 2>&1; then
        bs_log "command ${_cmd} not found"
        exit -1
    fi
}

# install_dotfile orig dest
install_dotfile() {
    local _orig="$1"
    local _dest="$2"
    bs_log "installing ${_orig} to ~/${_dest}"
    install -D -m 644 "${BASEDIR}/dotfiles/${_orig}" ~/"${_dest}"
}

satisfy_requirements() {
    bs_log "installing requirements..."
    apt update
    apt install -y curl git zsh tmux vim-nox htop rsync build-essential python3 python3-pip cmake sudo

    if [ "$?" -ne 0 ]; then
        bs_log "failed to call apt install"
        exit -1
    fi

    BASEDIR="$(mktemp -d)"
    if [ -z "$BASEDIR" ]; then
        bs_log "failed to create temp directory"
        exit -1
    fi
    bs_log "using $BASEDIR as temp directory"
}

download_dotfiles() {
    bs_log "clone repo into $BASEDIR"
    git clone "$REPO_URL" "$BASEDIR"

    if [ "$?" -ne 0 ]; then
        bs_log "failed to clone repo ${REPO_URL}"
        exit -1
    fi
}

install_omz() {
    bs_log "installing oh-my-zsh..."

    if [ -d ~/.oh-my-zsh ]; then
        bs_log "existing ~/.oh-my-zsh found, assume installed"
        return 0
    fi

    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    install_dotfile zshrc .zshrc
    bs_log "done"
}

install_vim_plug() {
    bs_log "installing vim-plug..."
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    install_dotfile vimrc .vimrc
    install_dotfile vim/ycm_extra_conf.py .vim/.ycm_extra_conf.py
    install_dotfile vim/go.vim .vim/ftplugin/go.vim
    bs_log "done"
}

install_tpm() {
    bs_log "installing tpm"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    install_dotfile tmux.conf .tmux.conf
    bs_log "done"
}

cleanup() {
    bs_log "clean up $BASEDIR"
    rm -rf "$BASEDIR"
}

check_root
check_cmd apt
check_cmd mktemp
check_cmd install

satisfy_requirements
download_dotfiles

install_omz
install_vim_plug
install_tpm

cleanup

bs_log "done"

